Smp.Presantation1/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Models.DTOs;
using SMP.Application.Services.AppUserService;

namespace Smp.Presantation1.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class UserController : Controller
    {

        private readonly IAppUserService _appUserService;


        public UserController(IAppUserService appUserService)
        {
   

            _appUserService = appUserService;

        }



        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Users(string userName)
        {
            return View(await _appUserService.GetUserName(userName));




        }

        
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            await _appUserService.Delete(id);
            return RedirectToAction("User", "Users");
        }

        [HttpGet]
        public IActionResult LogIn(string returnUrl = "/")
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["ReturnUrl"] = returnUrl;
            return View();

        }


        [HttpPost]
        public async Task<IActionResult> LogIn(LoginDTO model)
        {

            if (ModelState.IsValid)
            {
                var result = await _appUserService.Login(model);

                if (result.Succeeded)
                {
                    return RedirectToAction("AllPostsUser", "Post");
                }

                TempData["Warning"] = "Invalid log in credantial..!!";
            }



            return RedirectToAction("Index", "Home");
        }




        private IActionResult RedirectToLocal(string returnUrl)
        {



            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }


        public async Task<IActionResult> logOut()
        {
            await _appUserService.LogOut();
            //await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");

        }        
    }
}

Smp.Presantation1/Controllers/FollowController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Extensions;
using SMP.Application.Models.DTOs;
using SMP.Application.Services.FollowService;

namespace Smp.Presantation1.Controllers
{
    public class FollowController : Controller
    {
        private readonly IFollowService _followService;

        public FollowController(IFollowService followService)
        {
            _followService = followService;
        }

        [HttpPost]

        public async Task<IActionResult> Create(CreateFollowerDTO model, string id)
        {
           
           
            model.FollowingId = id;
            model.FollowerId = User.GetUserId();
            var follow = await _followService.IsFollowExsist(model);

            if (follow != false)
            {
                TempData["Warning"] = $"The {model.FollowingId} category already exist....!";
                return RedirectToAction("User","Details");
            }
            else
            {
                model.FollowingId = id;
                model.FollowerId = User.GetUserId();
                await _followService.Create(model);
                TempData["Success"] = $"The {model.FollowingId} has been added..!";
                return RedirectToAction("User", "Details");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            await _followService.Delete(id,User.GetUserId());
            return RedirectToAction("User", "Profile");
        }

        [HttpGet]
        public async Task<IActionResult> Followings(string id)
        {
   
            return View(await _followService.GetFollowings(id));
        }

        [HttpGet]
        public async Task<IActionResult> Followers(string id)
        {
            return View(await _followService.GetFollowers(id));
        }
    }
}

Smp.Presantation1/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Extensions;
using SMP.Application.Models.DTOs;
using SMP.Application.Services.PostService;

namespace Smp.Presantation1.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;


        public PostController(IPostService postService)
        {
            _postService = postService;

        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(PostDTO model)
        {
            if (ModelState.IsValid)
            {
                model.User_Id = User.GetUserId();
                if (model.User_Id == User.GetUserId())
                {
                    await _postService.Create(model);
                    return RedirectToAction("UserPosts");
                }
                else
                {
                    return RedirectToAction("Create");

                }
            }
            else
            {
                return BadRequest(String.Join(Environment.NewLine, ModelState.Values.SelectMany(h => h.Errors).Select(h => h.ErrorMessage + "" + h.Exception)));
            }
        }

        public async Task<IActionResult> Details(int id)
        {

           return  View(await _postService.GetPostDetails(id));
        }
        public async Task<IActionResult> UserPosts()
        {

           
            var model = await _postService.UserGetPosts(User.GetUserId());
            return View(model);



        }

        [HttpGet]
        public async Task<IActionResult> AllPosts()
        {
            var model = await _postService.GetPostsForMembers(User.GetUserId());


            return View(model);



        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var model = await _postService.GetById(id);
            ViewData["uploadPath"] = model.ImagePath;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(PostDTO model)
        {
            if (ModelState.IsValid)
            {
                await _postService.Update(model);
                TempData["Success"] = "Post has been added..!!";
                return RedirectToAction("UserProfile","User");


            }
            else
            {
                TempData["Error"] = "Post hasn't been added..!!";
                return View(model);
            }

        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _postService.Delete(id);
            return RedirectToAction("User", "UserProfile");
        }

       



    }



}

Smp.Presantation1/Controllers/PostSharingController.cs
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Extensions;
using SMP.Application.Models.DTOs;
using SMP.Application.Services.PostSharingService;

namespace Smp.Presantation1.Controllers
{
    public class PostSharingController : Controller
    {
        private readonly IPostSharingService _postSharingService;
        public PostSharingController(IPostSharingService postSharingService)
        {
            _postSharingService = postSharingService;

        }

        [HttpPost]

        public async Task<IActionResult> Create(PostSharingDTO model, int id)
        {


            model.PostId = id;
            model.UserId = User.GetUserId();
            var sharePost = await _postSharingService.IsRegisteredPostExsist(id);

            if (sharePost != false)
            {
                TempData["Warning"] = $"The {model.PostId} category already exist..!";
                return RedirectToAction("User", "Details");
            }
            else
            {
                model.PostId = id;
                model.UserId = User.GetUserId();
                await _postSharingService.Create(model);
                TempData["Success"] = $"The {model.PostId} has been added..!";
                return RedirectToAction("User", "Details");
            }
            
            
        


        }
        
        [HttpPost]

        public async Task<IActionResult> Delete(string id)
        {
            await _postSharingService.Delete(int.Parse(id));
            return RedirectToAction("User", "UserProfile");
        }
    }
}

Smp.Presantation1/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Extensions;
using SMP.Application.Models.DTOs;
using SMP.Application.Models.VMs;
using SMP.Application.Services.AppUserService;
using SMP.Application.Services.FollowService;
using SMP.Domain.Models.Entities;

namespace Smp.Presantation1.Controllers
{
    public class UserController : Controller
    {
        private readonly IAppUserService _appUserService;

        private readonly IFollowService _followService;
        public UserController(IAppUserService appUserService, IFollowService followService)
        {
            _followService = followService;

            _appUserService = appUserService;

        }






        [Route("google-login")]
        public IActionResult GoogleLogin()
        {
            var properties = new AuthenticationProperties { RedirectUri = Url.Action("GoogleResponse") };
            return Challenge(properties, GoogleDefaults.AuthenticationScheme);
        }



        [Route("google-response")]
        public async Task<IActionResult> GoogleResponse()
        {
            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            var claims = result.Principal.Identities.FirstOrDefault().Claims.Select(claim => new
            {
                claim.Issuer,
                claim.OriginalIssuer,
                claim.Type,
                claim.Value
            });

            return Json(claims);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == User.GetUserId())
            {
                return RedirectToAction("UserProfile", "User");
            }
            var users = await _appUserService.UserDetails(id, User.GetUserId());
            return View(users);
        }

        public async Task<IActionResult> UserProfile()
        {

            var user = await _appUserService.UserProfile(User.GetUserId());
            return View(user);
        }



        public IActionResult Register()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");



            }


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterDTO model)
        {
            if (ModelState.IsValid == true)
            {
                var result = await _appUserService.Register(model);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(String.Empty, item.Description);
                    TempData["Warning"] = $"{item.Description}";
                }
            }

            return View(model);
        }

        //[AllowAnonymous]
        public IActionResult LogIn(string returnUrl = "/")
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["ReturnUrl"] = returnUrl;
            return View();

        }


        [HttpPost]
        public async Task<IActionResult> LogIn(LoginDTO model)
        {

            if (ModelState.IsValid)
            {
                var result = await _appUserService.Login(model);

                if (result.Succeeded)
                {
                    return RedirectToAction("AllPosts", "Post");
                }

                TempData["Warning"] = "Invalid log in credantial..!!";
            }



            return RedirectToAction("Index", "Home");
        }




        private IActionResult RedirectToLocal(string returnUrl)
        {



            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }


        public async Task<IActionResult> logOut()
        {
            await _appUserService.LogOut();
            //await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");

        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == User.GetUserId())
            {
                var user = await _appUserService.GetById(User.GetUserId());

                if (user == null)
                {
                    return NotFound();
                }
                else
                {


                    return View(user);
                }

            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }


        [HttpPost]
        public async Task<IActionResult> Edit(UpdateProfilDTO model)
        {
            if (ModelState.IsValid)
            {
                await _appUserService.UpdateUser(model);
                TempData["Success"] = "Your profile has been edited..!!";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["Error"] = "Your profile hasn't been edited..!!";
                return RedirectToAction("Edit");
            }


        }




        [HttpGet]
        public async Task<IActionResult> Users(string userName)
        {
            return View(await _appUserService.GetUserName(userName));




        }
    }
}

Smp.Presantation1/Views/User/Details.cshtml
@model GetAppUserVM
@{
    ViewData["Title"] = "Details";
}



<form id="userDetails" novalidate class="needs-validation">
    <div class="card-body box-profile">
        <div class="text-center">
            <img class="profile-user-img img-fluid img-circle" src="@Model.ImagePath" alt="User profile picture">
        </div>

        <h3 class="profile-username text-center">@Model.UserName</h3>

        <li class="list-group-item">
            <b>User_Score</b> <a class="float-right">@Model.User_Score</a>
        </li>

        <ul class="list-group list-group-unbordered mb-3">
            <li class="list-group-item">
                <a asp-controller="Follow" asp-action="Followers" asp-route-id="@Model.Id">Followers</a>  <a class="float-right">@Model.Follower_Count</a>
            </li>
            <li class="list-group-item">
                <a asp-controller="Follow" asp-action="Followings" asp-route-id="@Model.Id">Followings</a>  <a class="float-right">@Model.Following_Count</a>

            </li>


        </ul>






        @if (Model.Followers.Count != 0)
        {

            @foreach (var item in Model.Followers)
            {


                if (item.FollowerId == User.GetUserId())
                {
                    <button type="button" class="btn btn-danger" onclick="unfollow()">UnFollow</button>

                }
            }


           
               

        }
        else
        {
            <button type="button" class="btn btn-primary" onclick="following()">Follow</button>

        }






        <br />
        <br />
        <br />
        <br />

        @foreach (var item in Model.UserPosts)
        {
            <form asp-action="Details" asp-route-returnUrl="@ViewData["ReturnUrl"]">
                <div class="card card-widget">
                    <div class="card-header">
                        <div class="user-block">
                            <img class="img-circle" src="@item.UserImagePath" alt="User Image">
                            <span class="username"><a href="#">@item.UserName</a></span>
                            <span class="description">Shared publicly - @item.CreateDate.ToShortDateString()</span>
                        </div>
                        <!-- /.user-block -->
                </div>
                    <!-- /.card-header -->
                <div class="card-body">
                        <img class="img-fluid pad" src="@item.ImagePath" alt="Photo">
                        <br />
                        <h4 class="card-text">@item.Description</h4>
                        <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Details</a>


                        <span class="float-right text-muted">@item.Total_Score Score - @item.Total_Comment Comments</span>
                    </div>
                    <!-- /.card-body -->
                    <!-- /.card-footer -->

            </div>
            </form>
        }
        @foreach (var item in Model.SaharingPosts)
        {
            <form asp-action="UserProfile" asp-route-returnUrl="@ViewData["ReturnUrl"]">
                <div class="card card-widget">
                    <div class="card-header">
                        <div class="user-block">
                            <img class="img-circle" src="@item.UserImagePath" alt="User Image">
                            <span class="username"><a href="#">@item.UserName</a></span>
                            <span class="description">Shared publicly - @item.CreateDate.ToShortDateString()</span>
                        </div>
                        <!-- /.user-block -->
                </div>
                    <!-- /.card-header -->
                <div class="card-body">
                        <img class="img-fluid pad" src="@item.ImagePath" alt="Photo">
                        <br />
                        <h4 class="card-text">@item.Description</h4>
                        <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Details</a>


                        <a asp-controller="PostSharing" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Delete</a>
                        <span class="float-right text-muted">@item.Total_Score Score - @item.Total_Comment Comments</span>
                    </div>
                    <!-- /.card-body -->


            </div>
            </form>

        }




    </div>
</form>

<script type="text/javascript">


    function following() {


        $.ajax({
            type: 'POST',
            url: '/Follow/Create/',


            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: { id :'@Model.Id'},

            success: function (result) {
                alert('başarılı oldu ');
                console.log(result);
            },

        })
    }



    function unfollow() {


        $.ajax({
            type: 'POST',
            url: '/Follow/Delete/',


            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: { id :'@Model.Id'},

            success: function (result) {
                alert('başarılı oldu ');
                console.log(result);
            },

        })
    }

</script>

Smp.Presantation1/Views/User/Edit.cshtml
@model UpdateProfilDTO
@{
    ViewData["Title"] = "Edit";
}

<div class="col-sm-6">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Edit Profile</h4>
        </div>
        <form asp-action="Edit" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <div class="card-body">
                <div class="form-group">
                    <label asp-for="UserName"></label>
                    <input asp-for="UserName" class="form-control" placeholder="User Name" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" placeholder="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" placeholder="Password" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword"></label>
                    <input asp-for="ConfirmPassword" class="form-control" placeholder="Confirm Password" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UploadPath"></label>
                    <input class="form-control" type="file" asp-for="UploadPath">
                    <span asp-validation-for="UploadPath" class="text-danger"></span>
                </div>
            </div>
            <div class="card-footer">
                <input type="submit" class="btn-success btn-sm float-end mr-2" value="Submit" />
                <a asp-action="Index" asp-controller="Home" class="btn-primary btn-sm float-end mr-2 ml-2">Home</a>
            </div>
        </form>
    </div>
</div>

Smp.Presantation1/Views/User/LogIn.cshtml
@model LoginDTO
@{
    ViewData["Title"] = "Login";
}
<div class="row">
    <div class="col-4 offset-4">
        <h1 class="display-4 border-bottom text-center pb-2">@ViewData["Title"]</h1>
    </div>
</div>

<div class="row">

    <div class="col-4 offset-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger small"></div>

            <div class="form-group mb-3">
                <label asp-for="UserName" class="form-label">Username</label>
                <input asp-for="UserName" class="form-control" placeholder="username" />
                <span asp-validation-for="UserName" class="text-danger small"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Password" class="form-label">Password</label>
                <input asp-for="Password" type="password" class="form-control" placeholder="password!" />
                <span asp-validation-for="Password" class="text-danger small"></span>
            </div>

            <div class="form-group d-grid mb-3">
                <button type="submit" class="btn btn-primary d-block"><i class="fa-solid fa-right-to-bracket me-2"></i>Login</button>
            </div>
        </form>
    </div>
</div>

Smp.Presantation1/Views/User/UserProfile.cshtml
@model GetAppUserVM
@{
    ViewData["Title"] = "UserProfile";
}





<form id="userDetails" novalidate class="needs-validation">
    <div class="card-body box-profile">
        <div class="text-center">
            <img class="profile-user-img img-fluid img-circle" src="@Model.ImagePath" alt="User profile picture">
        </div>

        <h3 class="profile-username text-center">@Model.UserName</h3>

        <li class="list-group-item">
            <b>User_Score</b> <a class="float-right">@Model.User_Score</a>
        </li>


        <ul class="list-group list-group-unbordered mb-3">
            <li class="list-group-item">
                <a asp-controller="Follow" asp-action="Followers" asp-route-id="@Model.Id">Followers</a>  <a class="float-right">@Model.Follower_Count</a>
            </li>
            <li class="list-group-item">
                <a asp-controller="Follow" asp-action="Followings" asp-route-id="@Model.Id">Followings</a>  <a class="float-right">@Model.Following_Count</a>

            </li>


        </ul>


        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning btn-sm">Edit</a>

    </div>
    @foreach (var item in Model.UserPosts)
    {
        <form asp-action="UserProfile" asp-route-returnUrl="@ViewData["ReturnUrl"]">
            <div class="card card-widget">
                <div class="card-header">
                    <div class="user-block">
                        <img class="img-circle" src="@item.UserImagePath" alt="User Image">
                        <span class="username"><a href="#">@item.UserName</a></span>
                        <span class="description">Shared publicly - @item.CreateDate.ToShortDateString()</span>
                    </div>
                    <!-- /.user-block -->
            </div>
                <!-- /.card-header -->
            <div class="card-body">
                    <img class="img-fluid pad" src="@item.ImagePath" alt="Photo">
                    <br />
                    <h4 class="card-text">@item.Description</h4>
                    <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Details</a>
                    <a asp-controller="Post" asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Update</a>
  
                    <span class="float-right text-muted">@item.Total_Score Score - @item.Total_Comment Comments</span>
                </div>
                <!-- /.card-body -->


        </div>
        </form>

    }
        @foreach (var item in Model.SaharingPosts)
    {
        <form asp-action="UserProfile" asp-route-returnUrl="@ViewData["ReturnUrl"]">
            <div class="card card-widget">
                <div class="card-header">
                    <div class="user-block">
                        <img class="img-circle" src="@item.UserImagePath" alt="User Image">
                        <span class="username"><a href="#">@item.UserName</a></span>
                        <span class="description">Shared publicly - @item.CreateDate.ToShortDateString()</span>
                    </div>
                    <!-- /.user-block -->
            </div>
                <!-- /.card-header -->
            <div class="card-body">
                    <img class="img-fluid pad" src="@item.ImagePath" alt="Photo">
                    <br />
                    <h4 class="card-text">@item.Description</h4>
                    <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Details</a>
           

                    <a asp-controller="PostSharing" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Un Sharring</a>
                    <span class="float-right text-muted">@item.Total_Score Score - @item.Total_Comment Comments</span>
                </div>
                <!-- /.card-body -->


        </div>
        </form>

    }



</form>

Smp.Presantation1/Views/User/Users.cshtml
@model List<GetAppUserVM>
@{
    ViewData["Title"] = "Users";
}




<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <h4>User List</h4>
        </div>
        <div class="card-body">
            <p>
                

                @using(Html.BeginForm("Users","User", FormMethod.Get))
                {
                    @Html.TextBox("userName") <input type="submit" value="Search" />


                    
                }                


            </p>

            <table class="table table-hover">
                <thead>
                    <tr>

                        <th>User Name</th>
                        <th>Image</th>
                        <th>User SCORE</th>

                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count() == 0)
                    {
                        <tr>
                        <td colspan="3">No records found.</td>
                        </tr>
                    }
                    else
                    {
                         @foreach (var item in Model)
                       {
                        <tr>
                            <td>
                                <a asp-controller="User" asp-action="Details" asp-route-id="@item.Id">@item.UserName</a>
                            </td>

                            <td>
                                <img src="@item.ImagePath" width="100" height="100">
                            </td>
                            <td>@item.User_Score</td>

                            <td>
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Details</a>
                            </td>

                         </tr>
                        }
                    }

                </tbody>
            </table>
        </div>

    </div>
</div>