Smp.Presantation1/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Services.PostService;

namespace Smp.Presantation1.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class PostController : Controller
    {
        private readonly IPostService _postService;


        public PostController(IPostService postService)
        {
            _postService = postService;

        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> AllPostsUser(string userName)
        {
            var model = await _postService.GetAllPostsUserName(userName);


            return View(model);



        }

        public async Task<IActionResult> Details(int id)
        {

            return View(await _postService.GetPostDetails(id));
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _postService.Delete(id);
            return RedirectToAction("AllPostsUser", "Post");
        }
    }
}

Smp.Presantation1/Controllers/PostCommentController.cs
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Extensions;
using SMP.Application.Models.DTOs;
using SMP.Application.Services.PostCommentService;

namespace Smp.Presantation1.Controllers
{
    public class PostCommentController : Controller
    {
        private readonly IPostCommentService _postCommentService;
        public PostCommentController(IPostCommentService postCommentService)
        {
            _postCommentService = postCommentService;
        }

        
        [HttpPost]

        public async Task<IActionResult> Create(string comment, int postId)
        {



            if (comment == null)
            {
                TempData["Warning"] = $"The {comment} category already exist..!";
                return RedirectToAction("Details", "Post", routeValues: new { id = postId });
            }
            else
            {
                CreatePostCommentDTO post_comment = new CreatePostCommentDTO();
                post_comment.PostId = postId;
                post_comment.UserId = User.GetUserId();
                post_comment.Text = comment;


                await _postCommentService.Create(post_comment);
                TempData["Success"] = $"The {post_comment.PostId} has been added..!";

                return RedirectToAction("Details", "Post", routeValues: new { id = postId });
            }
        }

        public async Task<IActionResult> Delete(int id, int postId)
        {
            await _postCommentService.Delete(id);
            return RedirectToAction("Details", "Post", routeValues: new { id = postId });

        }

    }
}

Smp.Presantation1/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Extensions;
using SMP.Application.Models.DTOs;
using SMP.Application.Services.PostService;

namespace Smp.Presantation1.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;


        public PostController(IPostService postService)
        {
            _postService = postService;

        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(PostDTO model)
        {
            if (ModelState.IsValid)
            {
                model.User_Id = User.GetUserId();
                if (model.User_Id == User.GetUserId())
                {
                    await _postService.Create(model);
                    return RedirectToAction("UserPosts");
                }
                else
                {
                    return RedirectToAction("Create");

                }
            }
            else
            {
                return BadRequest(String.Join(Environment.NewLine, ModelState.Values.SelectMany(h => h.Errors).Select(h => h.ErrorMessage + "" + h.Exception)));
            }
        }

        public async Task<IActionResult> Details(int id)
        {

           return  View(await _postService.GetPostDetails(id));
        }
        public async Task<IActionResult> UserPosts()
        {

           
            var model = await _postService.UserGetPosts(User.GetUserId());
            return View(model);



        }

        [HttpGet]
        public async Task<IActionResult> AllPosts()
        {
            var model = await _postService.GetPostsForMembers(User.GetUserId());


            return View(model);



        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var model = await _postService.GetById(id);
            ViewData["uploadPath"] = model.ImagePath;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(PostDTO model)
        {
            if (ModelState.IsValid)
            {
                await _postService.Update(model);
                TempData["Success"] = "Post has been added..!!";
                return RedirectToAction("UserProfile","User");


            }
            else
            {
                TempData["Error"] = "Post hasn't been added..!!";
                return View(model);
            }

        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _postService.Delete(id);
            return RedirectToAction("User", "UserProfile");
        }

       



    }



}

Smp.Presantation1/Views/Post/AllPosts.cshtml
@model List<GetPostVM>
@{
    ViewData["Title"] = "AllPosts";
}


<form id="allPosts" novalidate class="needs-validation">
    <div class="card-footer">
        <a asp-action="Create" class="btn btn-primary">Create New One</a>
    </div>
    <div class="col-sm-6">
        <div class="row">
            <div class="card-body">
                @foreach (var item in Model)
                {
                    <form asp-action="UserProfile" asp-route-returnUrl="@ViewData["ReturnUrl"]">
                        <div class="card card-widget">
                            <div class="card-header">
                                <div class="user-block">
                                    <img class="img-circle" src="@item.UserImagePath" alt="User Image">
                                    <a asp-controller="User" asp-action="Details" asp-route-id="@item.User_Id">@item.UserName</a>
                                    <span class="description">Shared publicly - @item.CreateDate</span>
                                </div>
                                <!-- /.user-block -->
                        </div>
                            <!-- /.card-header -->
                        <div class="card-body">
                                <img class="img-fluid" src="@item.ImagePath" alt="Photo">
                                <br />
                                <h4 class="card-text">@item.Description</h4>
                                <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Details</a>

                            </div>
                            <!-- /.card-body -->


                    </div>
                    </form>
                }
            </div>
        </div>

    </div>
    </div>



</form>

Smp.Presantation1/Views/Post/Details.cshtml
@model PostDetailsVM
@{
    ViewData["Title"] = "Details";
}

<div class="card card-widget">
    <div class="card-header">
        <div class="user-block">
            <img class="img-circle" src="@Model.UserImagePath" alt="User Image">
            <a asp-controller="User" asp-action="Details" asp-route-id="@Model.User_Id">@Model.UserName</a>
            <span class="description">Shared publicly - @Model.CreateDate.ToShortDateString()</span>
        </div>
        <!-- /.user-block -->
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <img class="img-fluid pad" src="@Model.ImagePath" alt="Photo">
        <br />
        <h4 class="card-text">@Model.Description</h4>
        <button type="button" class="btn btn-success btn-sm" onclick="share()"> Share</button>
        @if (User.GetUserId() != Model.User_Id)
        {
            <input name=opacity id="score" type="number" min=0 max=10 step=0.1 placeholder="0-10">
            <button type="button" class="btn btn-primary btn-sm" onclick="score()">Score</button>
        }


        <button type="button" class="btn btn-info btn-sm" onclick="favorite()">Favorite</button>
        @if (Model.User_Id == User.GetUserId())
        {
            <a asp-controller="Post" asp-action="Update" asp-route-id="@Model.Id" class="btn btn-warning btn-sm">Update</a>
           

            <button type="button" class="btn btn-danger btn-sm"  onclick="PostDelete1()" >Delete</button>

        }
        <span class="float-right text-muted">@Model.Total_Score Score - @Model.Total_Comment Comments</span>
    </div>
    <!-- /.card-body -->
    @foreach (var c in Model.Comments)
    {
        <div class="card-footer card-comments"  id="comment3">


            <div class="card-comment" id="commentUser" >
                <img class="img-circle img-sm" src="@c.UserImage" alt="User Image">
                <div class="comment-text">
                    <span class="username">
                        @c.UserName
                        <span class="text-muted float-right">@c.CreateDate</span>
                    </span>
                    @c.Text
                    @if (c.User_Id == User.GetUserId())
                    {
                        <button type="button" class="btn btn-warning btn-sm" id="commentDlt" data-id="@c.Id" onclick="commentDelete()">Delete</button>

                        
                    }
                </div>
            </div>
        </div>
    }

    <div class="card-footer">
        <form action="#" method="post">

            <div class="img-push">
                <input type="text" id="comment2" class="form-control form-control-sm" placeholder="Press enter to post comment">
                <button type="button" class="btn btn-warning btn-sm" onclick="comment3()">Comment</button>



            </div>
        </form>
    </div>
    <!-- /.card-footer -->
</div>

<script type="text/javascript">


    function commentDelete(){
        
        var id = $('#commentDlt').data('id');
        var url = '@Url.Action("Delete", "PostComment")';
        $.ajax({
            url: url,
            type: 'POST',
            data: { id: id , postId:'@Model.Id'},
            success: function (data) {
                alert("Silme işlemi başarılı");
                $('#commentUser').remove();
            }
        });
    };



    
    //$(function(){
        
    //    $("#comment").on("click", "btn-sm" , function()
    //     {
    //        var id = $(this).data("id");
    //        var comment = $("#comment2").val();
    //        $.ajax({
    //            url: "/PostComment/Create",
    //            type: "POST",
    //            data: {
    //                Post_Id: id,
    //                Text: comment
    //            },
    //            success: function(data)
    //            {
    //                $("#comment").append(data);
    //            }
    //        });
    //    });
        
        
        
    //});
    


    

    
    
    function share() {


        $.ajax({
            type: 'POST',
            url: '/PostSharing/Create/',


            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: { id :'@Model.Id'},

            success: function (result) {
                alert('You have successfully shared this post on your profile. ');
                console.log(result);
            },

        })
    }

    function score() {

        var score = $('#score').val();

        $.ajax({
            type: 'POST',
            url: '/PostScore/Create/',


            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: { postId :'@Model.Id',
            score: score},

            success: function (result) {
                alert('You have successfully rated this post.');
                console.log(result);
            },

        })
    }

    function favorite() {


        $.ajax({
            type: 'POST',
            url: '/FavoritePost/Create/',


            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: { id :'@Model.Id'},

            success: function (result) {
                alert('This post has been successfully added to your favorites. ');
                console.log(result);
            },

        })
    }

    function comment3() {
       var comment2 = $('#comment2').val();
        $.ajax({
            type: 'POST',
            url: '/PostComment/Create/',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: { postId :'@Model.Id',
            comment: comment2},
            success: function (result) {
                alert('You have successfully commented on this post.');
                console.log(result);
            },
        })
    }




     
    function PostDelete1() {


        $.ajax({
            type: 'POST',
            url:'/Post/Delete/',


            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: { id:'@Model.Id'},

            success: function (result) {
                alert('The post was successfully deleted.');
                console.log(result);
            },

        })
    }










</script>

Smp.Presantation1/Views/Post/Update.cshtml
@model PostDTO
@{
    ViewData["Title"] = "Update";
}


@if (Model.User_Id == User.GetUserId())
{


    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Edit Profile</h4>
            </div>
            <form asp-action="Update" enctype="multipart/form-data">

                <input type="hidden" asp-for="ImagePath" />
                <input type="hidden" asp-for="User_Id" />
                <input type="hidden" asp-for="Id" />
                <div class="card-body">
                        <img class="img-fluid pad" src="@Model.ImagePath" alt="Photo">
                        <br />
                  </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label asp-for="Description"></label>
                                <input asp-for="Description" class="form-control" placeholder="Email" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="card-footer">
                            <input type="submit" class="btn-success btn-sm float-end mr-2" value="Submit" />
                            <a asp-action="Index" asp-controller="Home" class="btn-primary btn-sm float-end mr-2 ml-2">Home</a>
                        </div>
            </form>
        </div>
    </div>
    @*    <div class="row ml-2 mt-2 mr-2">
        <div class="col-sm-6">
        <div class="card card-primary">
        <div class="card-header">
        <h3 class="card-title">Create Post</h3>
        </div>
        <form asp-action="Create" enctype="multipart/form-data">
        <div class="card-body">
        <input type="hidden" asp-for="Id" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">

        <label asp-for="UploadPath"></label>
        <input type="hidden" asp-for="UploadPath"/>
        <span asp-validation-for="UploadPath" class="text-danger"></span>
        </div>
        <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" placeholder="Content" asp-for="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        </div>
        <div class="card-footer">
        <a asp-action="List" class="btn btn-dark btn-sm mr-2 float-end">Back To List</a>
        <input type="submit" class="btn btn-primary btn-sm float-end mr-2" value="Submit" />
        </div>
        </form>
        </div>
        </div>
        </div>*@
}

Smp.Presantation1/Views/Post/UserPosts.cshtml
@model List<GetPostVM>
@{
    ViewData["Title"] = "UserPosts";
}

@*<div class="col-sm-6">
    <div class="row">
    <div class="card-header">
    <h4>User Post List</h4>
    </div>
    <div class="card-body">
    <table class="table table-hover">
    <tbody>
    @foreach (var item in Model)
    {
    <tr>
    <td>@item.Id</td>
    <td>@item.Description</td>
    <td>@item.ImagePath</td>
    <td>@item.Post_Scores</td>
    <td>@item.CreateDate</td>

    <td>
    <a asp-action="Post_Comments" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Post_Comments</a>
    </td>
    <td>
    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Delete</a>
    </td>

    </tr>
    }
    </tbody>

    </table>
    </div>
    <div class="card-footer">
    <a asp-action="Create" class="btn btn-primary">Create New One</a>
    </div>
    </div>
    </div>*@
@foreach (var item in Model)
{
    <form asp-action="Details" asp-route-returnUrl="@ViewData["ReturnUrl"]">
        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <img class="img-circle" src="@item.UserImagePath" alt="User Image">
                    <span class="username"><a href="#">@item.UserName</a></span>
                    <span class="description">Shared publicly - @item.CreateDate.ToShortDateString()</span>
                </div>
                <!-- /.user-block -->
        </div>
            <!-- /.card-header -->
        <div class="card-body">
                <img class="img-fluid pad" src="@item.ImagePath" alt="Photo">
                <br />
                <h4 class="card-text">@item.Description</h4>
                <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Details</a>


                <span class="float-right text-muted">@item.Total_Score Score - @item.Total_Comment Comments</span>
            </div>
            <!-- /.card-body -->
            <!-- /.card-footer -->

    </div>
    </form>
}