Smp.Presantation1/Controllers/FavoritePostController.cs
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Extensions;
using SMP.Application.Models.DTOs;
using SMP.Application.Services.FavoritePostService;

namespace Smp.Presantation1.Controllers
{
    public class FavoritePostController : Controller
    {
        private readonly IFavoritePostService _favoritePostService;
        public FavoritePostController(IFavoritePostService favoritePostService)
        {
            _favoritePostService = favoritePostService;

        }

        [HttpPost]

        public async Task<IActionResult> Create(CreateFavoritePost model, int id)
        {


            model.PostId = id;
            model.UserId = User.GetUserId();
            var favoritePost = await _favoritePostService.IsFavoriteExsist(id, User.GetUserId());

            if (favoritePost != false)
            {
                TempData["Warning"] = $"The {model.PostId} category already exist..!";
                return RedirectToAction("User", "Details");
            }
            else
            {
                model.PostId = id;
                model.UserId = User.GetUserId();
                await _favoritePostService.Create(model);
                TempData["Success"] = $"The {model.PostId} has been added..!";
                return RedirectToAction("User", "Details");
            }

        }
        
        [HttpGet]
        public async Task<IActionResult> FavoritePosts()
        {
            var model = await _favoritePostService.GetFavoritePosts(User.GetUserId());
            return View(model);



        }
        public async Task<IActionResult> Delete(int id)
        {
            await _favoritePostService.Delete(id);
            return RedirectToAction("FavoritePost", "FavoritePosts");
        }


    }
}

Smp.Presantation1/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using SMP.Application.Extensions;
using SMP.Application.Models.DTOs;
using SMP.Application.Services.PostService;

namespace Smp.Presantation1.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;


        public PostController(IPostService postService)
        {
            _postService = postService;

        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(PostDTO model)
        {
            if (ModelState.IsValid)
            {
                model.User_Id = User.GetUserId();
                if (model.User_Id == User.GetUserId())
                {
                    await _postService.Create(model);
                    return RedirectToAction("UserPosts");
                }
                else
                {
                    return RedirectToAction("Create");

                }
            }
            else
            {
                return BadRequest(String.Join(Environment.NewLine, ModelState.Values.SelectMany(h => h.Errors).Select(h => h.ErrorMessage + "" + h.Exception)));
            }
        }

        public async Task<IActionResult> Details(int id)
        {

           return  View(await _postService.GetPostDetails(id));
        }
        public async Task<IActionResult> UserPosts()
        {

           
            var model = await _postService.UserGetPosts(User.GetUserId());
            return View(model);



        }

        [HttpGet]
        public async Task<IActionResult> AllPosts()
        {
            var model = await _postService.GetPostsForMembers(User.GetUserId());


            return View(model);



        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var model = await _postService.GetById(id);
            ViewData["uploadPath"] = model.ImagePath;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(PostDTO model)
        {
            if (ModelState.IsValid)
            {
                await _postService.Update(model);
                TempData["Success"] = "Post has been added..!!";
                return RedirectToAction("UserProfile","User");


            }
            else
            {
                TempData["Error"] = "Post hasn't been added..!!";
                return View(model);
            }

        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _postService.Delete(id);
            return RedirectToAction("User", "UserProfile");
        }

       



    }



}

Smp.Presantation1/Views/FavoritePost/FavoritePosts.cshtml
@model List<FavoritePostVM>
@{
    ViewData["Title"] = "FavoritePosts";
}

<form id="allPosts" novalidate class="needs-validation">

    <div class="col-sm-6">
        <div class="row">
            <div class="card-header">
                <h4>Favorite Posts</h4>
            </div>
            <div class="card-body">
                @foreach (var item in Model)
                {
                    <form asp-action="UserProfile" asp-route-returnUrl="@ViewData["ReturnUrl"]">
                        <div class="card card-widget">
                            <div class="card-header">
                                <div class="user-block">
                                    <img class="img-circle" src="@item.UserImagePath" alt="User Image">
                                    <span class="username"><a href="#">@item.UserName</a></span>
                                    <span class="description">Shared publicly - @item.CreateDate</span>
                                </div>
                                <!-- /.user-block -->
                        </div>
                            <!-- /.card-header -->
                        <div class="card-body">
                                <img class="img-fluid pad" src="@item.PostImage" alt="Photo">
                                <br />
                                <h4 class="card-text">@item.Description</h4>
                                <a asp-controller="Post" asp-action="Details" asp-route-id="@item.Post_Id" class="btn btn-warning btn-sm">Details</a>
                                <a asp-controller="FavoritePost" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Remove</a>
                                <span class="float-right text-muted">@item.Total_Score Score - @item.Total_Comment Comments</span>
                            </div>
                            <!-- /.card-body -->


                    </div>
                    </form>
                }
            </div>

        </div>
    </div>



</form>